"use client"
import React from "react"
import Link from "next/link"
import Userheader from '../../components/Userheader'
import Userfooter from '../../components/Userfooter'
import Leftsidemenu from '../../components/Leftsidemenu'
import { Container, Image, Form, Button } from 'react-bootstrap'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons';
const Desktoppage = () => {
    return (
        <div className="pagecontent gridpagecontent innerpagegrid">
            <div className="backgroundoverlay" id="backgroundoverlay"></div>
            <Userheader />
            <Leftsidemenu />
            <article className="gridparentbox">
                <Container className="sitecontainer">
                    <div className="innerpagecontent">
                        <h2 className="h2 text-start"><Link href="/security" className="alink"><span className="me-2"><FontAwesomeIcon icon={faAngleLeft} /></span></Link>Enable Google Authenticator</h2>
                    </div>
                    <div className="panelcontentbox mt-3">
                        <div className="securitycontentbox authbg">
                            <Form className='siteformbg'>
                                <div className="secttable table-content">
                                    <div> <span className="numiconb">1</span> </div>
                                    <div>
                                        <h3>Install Google Authenticator</h3>
                                        <ul>
                                            <li> iOS users: Search “Google Authenticator” in the App Store. </li>
                                            <li> Android users: Search “Google Authenticator” in Google Play or your mobile browser. </li>
                                        </ul>
                                        <div className="d-flex gap-2"> <Image src="assets/images/playstore.svg" alt="img" className="apimg" /> <Image src="assets/images/apk.svg" alt="img" className="apimg" /> </div>
                                    </div>
                                </div>
                                <div className="secttable table-content">
                                    <div> <span className="numiconb">2</span> </div>
                                    <div>
                                        <h3>Add the Key to Google Authenticator</h3>
                                        <p className="content mb-2">Open the Google Authenticator app, then scan the QR code or manually enter the key shown below to add your verification token.</p>
                                        <div className="d-flex gap-3 align-items-center">
                                            <div className="qrimg">
                                                <Image src="assets/images/qrcode.png" alt="img" className="g-qr" />
                                            </div>
                                            <div className="google_code d-flex gap-2">
                                                <h5 className="h5">JZZFG3S6HA3DQMTH</h5>
                                                <div className="alink copy"><Image src="assets/images/copy.svg" alt='rq' width={100} height={100} /></div>
                                            </div>
                                        </div>
                                        <p className="content">Note: Save this backup key in a secure place. You will need it if you change your phone or lose access to your device.</p>
                                    </div>
                                </div>
                                <div className="secttable table-content">
                                    <div> <span className="numiconb">3</span> </div>
                                    <div>
                                        <h3>Enter the Verification Code</h3>
                                        <Form.Group className="form-group">
                                            <Form.Label>Enter the 6-digit code generated by Google Authenticator for the email: John**@gmail.com**</Form.Label>
                                            <Form.Control name="code" placeholder="Google 2fa code" id="code" />
                                        </Form.Group>
                                        <div className="mt-3">
                                            <Button className="sitebtn">Submit</Button>
                                        </div>
                                    </div>
                                </div>

                            </Form>
                        </div>
                    </div>
                </Container>
            </article>
            <Userfooter />
        </div>
    )
}

export default Desktoppage


